default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  prepared_statements: false

development:
  <<: *default
  database: loyalty_app_development
  username: postgres
  password: postgres

test:
  <<: *default
  database: sample_postgres_test
  username: postgres
  password: postgres

production:
  <<: *default
  database: sample_postgres_production
  username: postgres
  password: postgres